In [2]:
import torch
import torch.nn as nn

In [16]:
class MyConv(nn.Module):
    def __init__(self, kernel_size: int = 1):
        super(MyConv, self).__init__()
        self.kernel = nn.Parameter(torch.tensor(torch.rand(kernel_size, kernel_size), dtype = torch.float32).unsqueeze(0).unsqueeze(0))
        
    def forward(self, picture):
        # look at dims of input
        batch_size, n_channels, height, width = picture.size()
        k_height, k_width = self.kernel.size(2), self.kernel.size(3)

        #output size
        o_height, o_width = height - k_height + 1, width - k_width + 1
        
        #initilize output
        output = torch.tensor(torch.rand(o_height, o_width)).unsqueeze(0).unsqueeze(0)
        
        #perform convolution
        for i in range(o_height):
            for j in range(o_width):
                elem = torch.sum(picture[:, :, i:i+k_height, j:j+k_width] * self.kernel)
                output[:, :, i, j] = elem
        return output        
        

In [17]:
a = torch.rand(2, 2).unsqueeze(0).unsqueeze(0)
a

tensor([[[[0.9104, 0.5981],
          [0.7515, 0.3823]]]])

In [19]:
cnn = MyConv(kernel_size=2)
outp = cnn.forward(a)
print(outp)
print(cnn.kernel)

tensor([[[[1.5142]]]], grad_fn=<AsStridedBackward0>)
Parameter containing:
tensor([[[[0.8601, 0.4645],
          [0.2049, 0.7832]]]], requires_grad=True)


C:\Users\pasha\AppData\Local\Temp\ipykernel_28892\4275808789.py:4: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.kernel = nn.Parameter(torch.tensor(torch.rand(kernel_size, kernel_size), dtype = torch.float32).unsqueeze(0).unsqueeze(0))
C:\Users\pasha\AppData\Local\Temp\ipykernel_28892\4275808789.py:15: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  output = torch.tensor(torch.rand(o_height, o_width)).unsqueeze(0).unsqueeze(0)
