In [3]:
from sklearn.model_selection import train_test_split
import numpy as np

In [4]:
X, y = np.random.rand(10, 2), np.random.rand(10)

In [5]:
X, y

(array([[0.96169427, 0.15279307],
        [0.25217143, 0.90104521],
        [0.09077503, 0.41864781],
        [0.84341479, 0.37926503],
        [0.74174687, 0.0725599 ],
        [0.86219996, 0.05935711],
        [0.45396412, 0.04223812],
        [0.64596169, 0.19271987],
        [0.27370356, 0.86654815],
        [0.37076412, 0.38800182]]),
 array([0.92968721, 0.31197558, 0.13885281, 0.19442485, 0.25517576,
        0.38333445, 0.427572  , 0.52516085, 0.97938583, 0.57426618]))

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [9]:
X_train, X_test, y_train, y_test

(array([[0.45396412, 0.04223812],
        [0.84341479, 0.37926503],
        [0.96169427, 0.15279307],
        [0.86219996, 0.05935711],
        [0.09077503, 0.41864781],
        [0.64596169, 0.19271987],
        [0.37076412, 0.38800182]]),
 array([[0.25217143, 0.90104521],
        [0.27370356, 0.86654815],
        [0.74174687, 0.0725599 ]]),
 array([0.427572  , 0.19442485, 0.92968721, 0.38333445, 0.13885281,
        0.52516085, 0.57426618]),
 array([0.31197558, 0.97938583, 0.25517576]))

In [10]:
X_train.shape[0] == y_train.shape[0] and X_test.shape[0] == y_test.shape[0]

True